version: '3'
services:
  website:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/app
      - /app/knit/node_modules
      - knit-build:/app/knit/build
  nginx:
    image: nginx:1.19
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./software/html:/usr/share/nginx/software/html
      - knit-build:/usr/share/nginx/knit/html 
      - ./data/nginx:/etc/nginx/conf.d
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
  certbot:
    image: certbot/certbot:arm32v6-latest
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot

volumes:
  knit-build:
